#!/bin/sh -eu

BOX=${1:-./dist/build/box/box}

export BOX_STORE=test/cli/basic/v3
export BOX_USER=pwadler
export BOX_IDENTITY=~/.ssh/endofunctor_rsa
export BOX_KNOWN_HOSTS=/tmp/box_test_known_hosts
export BOX_ANSI_ESCAPES=0

$BOX -v

$BOX --version

if $BOX ip ::nomatches; then exit 1; fi
if $BOX; then exit 1; fi
$BOX ip mincom
$BOX ip acme
$BOX ip :lab
$BOX ip --external :lab
$BOX ip mincom:land
$BOX ip mincom:land:zoot
$BOX ip mincom:land:zoot.golden
$BOX ip mincom:land:golden
$BOX ip ::zoot.golden
$BOX ip :::i-a6g1d97a
$BOX ip :::i-fe6988ed
if $BOX ip acme:land; then exit 1; fi
if $BOX ip mincom:land:brown; then exit 1; fi
if $BOX ip mincom:land:kermit; then exit 1; fi
if $BOX ip mincom:hub; then exit 1; fi

check() {
  if [ "$1" != "$2" ]; then
    BOX_TEMP=$(mktemp -d 2>/dev/null || mktemp -d -t 'box')
    trap "rm -rf $BOX_TEMP" EXIT

    EXPECT_PIPE=$BOX_TEMP/expected
    ACTUAL_PIPE=$BOX_TEMP/actual

    mkfifo $EXPECT_PIPE
    mkfifo $ACTUAL_PIPE

    echo "$1" > $EXPECT_PIPE &
    echo "$2" > $ACTUAL_PIPE &

    diff -u $EXPECT_PIPE $ACTUAL_PIPE
    exit 1
  fi
}

EXPECT='["ssh","-o","ProxyCommand=ssh -i '$BOX_IDENTITY' -o UserKnownHostsFile=/tmp/box_test_known_hosts '$BOX_USER'@54.1.1.6 nc %h %p 2>/dev/null","-o","UserKnownHostsFile=/tmp/box_test_known_hosts","'$BOX_USER'@192.31.14.3"]'
ACTUAL=$($BOX --dry-run ssh acme:lab)
check "$EXPECT" "$ACTUAL"

EXPECT='kermit.brown.717'
ACTUAL=$($BOX ls | grep a6g1d97a | awk '{print $3}')
check "$EXPECT" "$ACTUAL"

EXPECT='ambiata'
ACTUAL=$($BOX ls ambiata | tail -1 | awk '{print $1}' | head)
check "$EXPECT" "$ACTUAL"

# Note needs to stay at the end.
EXPECT='Wile E. Coyote'
ACTUAL=$($BOX ls acme | grep i-defaced0 | awk '{for(i=(NF-2);i<=NF;i++){printf "%s ", $i}; printf "\n"}' | xargs)
check "$EXPECT" "$ACTUAL"

EXPECT='["ssh","-o","ProxyCommand=ssh -i '$BOX_IDENTITY' -o UserKnownHostsFile=/tmp/box_test_known_hosts '$BOX_USER'@54.1.1.6 nc %h %p 2>/dev/null","-o","UserKnownHostsFile=/tmp/box_test_known_hosts","'$BOX_USER'@192.31.14.3"]'
ACTUAL=$($BOX --dry-run ssh acme:lab)
check "$EXPECT" "$ACTUAL"

EXPECT='["autossh","-M","0","-o","ServerAliveInterval 30","-o","ServerAliveCountMax 3","-o","ProxyCommand=ssh -i '$BOX_IDENTITY' -o UserKnownHostsFile=/tmp/box_test_known_hosts '$BOX_USER'@54.1.1.6 nc %h %p 2>/dev/null","-o","UserKnownHostsFile=/tmp/box_test_known_hosts","'$BOX_USER'@192.31.14.3"]'
ACTUAL=$($BOX --dry-run ssh --auto acme:lab)
check "$EXPECT" "$ACTUAL"

# running box ssh in the background - pass -f as an ssh arg
EXPECT='["ssh","-o","ProxyCommand=ssh -i '$BOX_IDENTITY' -o UserKnownHostsFile=/tmp/box_test_known_hosts '$BOX_USER'@54.1.1.6 nc %h %p 2>/dev/null","-o","UserKnownHostsFile=/tmp/box_test_known_hosts","'$BOX_USER'@192.31.14.3","-f"]'
ACTUAL=$($BOX --dry-run ssh -b acme:lab)
check "$EXPECT" "$ACTUAL"

# with --auto, pass -f to autossh instead
EXPECT='["autossh","-f","-M","0","-o","ServerAliveInterval 30","-o","ServerAliveCountMax 3","-o","ProxyCommand=ssh -i '$BOX_IDENTITY' -o UserKnownHostsFile=/tmp/box_test_known_hosts '$BOX_USER'@54.1.1.6 nc %h %p 2>/dev/null","-o","UserKnownHostsFile=/tmp/box_test_known_hosts","'$BOX_USER'@192.31.14.3"]'
ACTUAL=$($BOX --dry-run ssh --auto -b acme:lab)
check "$EXPECT" "$ACTUAL"

EXPECT='["ssh","-i","'$BOX_IDENTITY'","-o","UserKnownHostsFile='$BOX_KNOWN_HOSTS'","'$BOX_USER'@54.1.1.6"]'
ACTUAL=$($BOX --dry-run ssh :gateway:)
check "$EXPECT" "$ACTUAL"

EXPECT=$(cat <<'EOF'
ip:Get the IP address of a box.
ssh:SSH to a box.
rsh:SSH to a box with a shell interface compatible with rsync.
rsync:Invoke rsync via box.
ls:List available boxes.
EOF
)
ACTUAL=$($BOX --zsh-commands)
check "$EXPECT" "$ACTUAL"

# Test -e flag is parsed correctly
echo "Testing -e flag parses correctly..."
EXPECT=$($BOX --help 2>&1)
ACTUAL=$($BOX -e altenv --help 2>&1)
check "$EXPECT" "$ACTUAL"

EXPECT=$($BOX --help 2>&1)
ACTUAL=$($BOX --environment customenv --help 2>&1)
check "$EXPECT" "$ACTUAL"

EXPECT=$($BOX --environment altenv ls)
ACTUAL=$($BOX -e altenv ls)
check "$EXPECT" "$ACTUAL"

# Test that bad env args don't run
echo "Testing invalid environment arg..."
EXPECT="Could not find the box file located at"
ACTUAL=$($BOX -e badenv ls 2>&1 | cut -d':' -f1)
check "$EXPECT" "$ACTUAL"

ACTUAL=$($BOX --environment badenv ls 2>&1 | cut -d':' -f1)
check "$EXPECT" "$ACTUAL"

# Test we get the correct set of values from altenv
echo "Testing with alt environment..."

CMD="$BOX -e altenv ip ambiata:totpadmin"
EXPECT="172.131.113.24"
echo $CMD
ACTUAL=$($CMD)
check "$EXPECT" "$ACTUAL"

CMD="$BOX -e altenv ip ambiata:totp:asg.totp.helium.blargho"
EXPECT="172.131.22.14"
echo $CMD
ACTUAL=$($CMD)
check "$EXPECT" "$ACTUAL"

# Test ssh finds correct params from correct env
CMD="$BOX -e altenv --dry-run ssh ambiata:totp:asg.totp.helium.blargho"
EXPECT='["ssh","-o","ProxyCommand=ssh -i '$BOX_IDENTITY' -o UserKnownHostsFile=/tmp/box_test_known_hosts '$BOX_USER'@54.22.33.6 nc %h %p 2>/dev/null","-o","UserKnownHostsFile=/tmp/box_test_known_hosts","'$BOX_USER'@172.131.22.14"]'
echo $CMD
ACTUAL=$($CMD)
check "$EXPECT" "$ACTUAL"

rm -f $BOX_KNOWN_HOSTS
