#!/bin/sh -eu

BOX=${1:-./dist/build/box/box}

export BOX_STORE=test/cli/basic/v2
export BOX_USER=pwadler
export BOX_IDENTITY=~/.ssh/endofunctor_rsa

$BOX -v

$BOX --version

if $BOX ip ::nomatches; then exit 1; fi
if $BOX; then exit 1; fi
$BOX ip mincom
$BOX ip acme
$BOX ip :lab
$BOX ip --external :lab
$BOX ip mincom:land
$BOX ip mincom:land:zoot
$BOX ip mincom:land:zoot.golden
$BOX ip mincom:land:golden
$BOX ip ::zoot.golden
$BOX ip :::i-a6g1d97a
$BOX ip :::i-fe6988ed
if $BOX ip acme:land; then exit 1; fi
if $BOX ip mincom:land:brown; then exit 1; fi
if $BOX ip mincom:land:kermit; then exit 1; fi
if $BOX ip mincom:hub; then exit 1; fi

function check() {
  if [ "$1" != "$2" ]; then
    echo "expected: $1"
    echo " but was: $2"
    exit 1
  fi
}

EXPECT='["ssh","-o","ProxyCommand=ssh -i '$BOX_IDENTITY' '$BOX_USER'@54.1.1.6 nc %h %p 2>/dev/null","-o","HostKeyAlias=box.acme.lab.kermit.brown.717.i-a6g1d97a.jump","'$BOX_USER'@192.31.14.3"]'
ACTUAL=$($BOX --dry-run ssh acme:lab)
check "$EXPECT" "$ACTUAL"

EXPECT='kermit.brown.717'
ACTUAL=$($BOX ls | grep a6g1d97a | awk '{print $3}')
check "$EXPECT" "$ACTUAL"

EXPECT='ambiata'
ACTUAL=$($BOX ls ambiata | tail -1 | awk '{print $1}' | head)
check "$EXPECT" "$ACTUAL"
